package com.shoes.admin.entry;

public class EntryInfo{

    private String entry_id;
    private int file_size;
    private String reg_id;
    private String upd_id;
    private String del_id;
    private String entry_sect;
    private String entry_type;
    private String entry_name;
    private String entry_product;
    private String entry_explan;
    private String entry_price;
    private String sch_sday;
    private String sch_eday;
    private String sch_oday;
    private String file_name;
    private String file_realname;
    private String file_path;
    private String file_ext;
    private String db_status;
    private String user_id;
    private String total_cnt;
    private String kiosk_status;
    private String reg_date;
    private String shoes_amount;
    private String shoes_name;
    private String shoes_price;
    private String shoes_explan;
    private String shoes_size;
    private String shoes_size_1;
    private String shoes_size_2;
    private String shoes_size_3;
    private String shoes_size_35;
    private String shoes_size_4;
    private String shoes_size_45;
    private String shoes_size_5;
    private String shoes_size_55;
    private String shoes_size_6;
    private String shoes_size_65;
    private String shoes_size_7;
    private String shoes_size_75;
    private String shoes_size_8;
    private String shoes_size_85;
    private String shoes_size_9;
    private String shoes_size_95;
    private String shoes_size_10;
    private String shoes_size_105;
    private String shoes_size_11;
    private String shoes_size_115;
    private String shoes_size_12;
    private String shoes_size_125;
    private String shoes_size_13;
    private String shoes_size_14;

    private String user_name;
    private String user_firstname;
    private String user_lastname;
    private String user_phone;
    private String user_mail;
    private String user_gender;
    private String user_age;
    private String user_birthday;

    private String m_cnt;
    private String f_cnt;

    private String ten_cnt;
    private String twenty_cnt;
    private String thirty_cnt;
    private String forty_cnt;
    private String fifty_cnt;
    private String winner_choice;
    private String winner_id;
    

    
    public void setEntry_id(String s){ this.entry_id = s; };
    public void setFile_size(int s){ this.file_size = s; };
    public void setReg_id(String s){ this.reg_id = s; };
    public void setUpd_id(String s){ this.upd_id = s; };
    public void setDel_id(String s){ this.del_id = s; };    
    public void setEntry_sect(String s){ this.entry_sect = s; };
    public void setEntry_type(String s){ this.entry_type = s; };
    public void setEntry_name(String s){ this.entry_name = s; };
    public void setEntry_product(String s){ this.entry_product = s; };
    public void setEntry_explan(String s){ this.entry_explan = s; };
    public void setEntry_price(String s){ this.entry_price = s; };
    public void setSch_sday(String s){ this.sch_sday = s; };
    public void setSch_eday(String s){ this.sch_eday = s; };
    public void setSch_oday(String s){ this.sch_oday = s; };
    public void setFile_name(String s){ this.file_name = s; };
    public void setFile_realname(String s){ this.file_realname = s; };
    public void setFile_path(String s){ this.file_path = s; };
    public void setFile_ext(String s){ this.file_ext = s; };
    public void setDb_status(String s){ this.db_status = s; };
    public void setUser_id(String s){ this.user_id = s; };
    public void setTotal_cnt(String s){ this.total_cnt = s; };
    public void setKiosk_status(String s){ this.kiosk_status = s; };
    public void setReg_date(String s){ this.reg_date = s; };
    public void setShoes_amount(String s){ this.shoes_amount = s; };
    public void setShoes_name(String s){ this.shoes_name = s; };
    public void setShoes_price(String s){ this.shoes_price = s; };
    public void setShoes_explan(String s){ this.shoes_explan = s; };
    public void setShoes_size(String s){ this.shoes_size = s; };
    public void setShoes_size_1(String s){ this.shoes_size_1 = s; };
    public void setShoes_size_2(String s){ this.shoes_size_2 = s; };
    public void setShoes_size_3(String s){ this.shoes_size_3 = s; };
    public void setShoes_size_35(String s){ this.shoes_size_35 = s; };
    public void setShoes_size_4(String s){ this.shoes_size_4 = s; };
    public void setShoes_size_45(String s){ this.shoes_size_45 = s; };
    public void setShoes_size_5(String s){ this.shoes_size_5 = s; };
    public void setShoes_size_55(String s){ this.shoes_size_55 = s; };
    public void setShoes_size_6(String s){ this.shoes_size_6 = s; };
    public void setShoes_size_65(String s){ this.shoes_size_65 = s; };
    public void setShoes_size_7(String s){ this.shoes_size_7 = s; };
    public void setShoes_size_75(String s){ this.shoes_size_75 = s; };
    public void setShoes_size_8(String s){ this.shoes_size_8 = s; };
    public void setShoes_size_85(String s){ this.shoes_size_85 = s; };
    public void setShoes_size_9(String s){ this.shoes_size_9 = s; };
    public void setShoes_size_95(String s){ this.shoes_size_95 = s; };
    public void setShoes_size_10(String s){ this.shoes_size_10 = s; };
    public void setShoes_size_105(String s){ this.shoes_size_105 = s; };
    public void setShoes_size_11(String s){ this.shoes_size_11 = s; };
    public void setShoes_size_115(String s){ this.shoes_size_115 = s; };
    public void setShoes_size_12(String s){ this.shoes_size_12 = s; };
    public void setShoes_size_125(String s){ this.shoes_size_125 = s; };
    public void setShoes_size_13(String s){ this.shoes_size_13 = s; };
    public void setShoes_size_14(String s){ this.shoes_size_14 = s; };
    public void setUser_name(String s){ this.user_name = s; };
    public void setUser_firstname(String s){ this.user_firstname = s; };
    public void setUser_lastname(String s){ this.user_lastname = s; };
    public void setUser_phone(String s){ this.user_phone = s; };
    public void setUser_mail(String s){ this.user_mail = s; };
    public void setUser_gender(String s){ this.user_gender = s; };
    public void setUser_age(String s){ this.user_age = s; };
    public void setUser_birthday(String s){ this.user_birthday = s; };
    public void setM_cnt(String s){ this.m_cnt = s; };
    public void setF_cnt(String s){ this.f_cnt = s; };
    public void setTen_cnt(String s){ this.ten_cnt = s; };
    public void setTwenty_cnt(String s){ this.twenty_cnt = s; };
    public void setThirty_cnt(String s){ this.thirty_cnt = s; };
    public void setForty_cnt(String s){ this.forty_cnt = s; };
    public void setFifty_cnt(String s){ this.fifty_cnt = s; }; 
    public void setWinner_choice(String s){ this.winner_choice = s; }; 
    public void setWinner_id(String s){ this.winner_id = s; }; 
    


    public String getEntry_id(){ return getChkNull(entry_id); };
    public int getFile_size(){ return file_size; };
    public String getReg_id(){ return getChkNull(reg_id); };
    public String getUpd_id(){ return getChkNull(upd_id); };
    public String getDel_id(){ return getChkNull(del_id); };
    public String getEntry_sect(){ return getChkNull(entry_sect); };
    public String getEntry_type(){ return getChkNull(entry_type); };
    public String getEntry_name(){ return getChkNull(entry_name); };
    public String getEntry_product(){ return getChkNull(entry_product); };
    public String getEntry_explan(){ return getChkNull(entry_explan); };
    public String getEntry_price(){ return getChkNull(entry_price); };
    public String getSch_sday(){ return getChkNull(sch_sday); };
    public String getSch_eday(){ return getChkNull(sch_eday); };
    public String getSch_oday(){ return getChkNull(sch_oday); };
    public String getFile_name(){ return getChkNull(file_name); };
    public String getFile_realname(){ return getChkNull(file_realname); };
    public String getFile_path(){ return getChkNull(file_path); };
    public String getFile_ext(){ return getChkNull(file_ext); };
    public String getDb_status(){ return getChkNull(db_status); };
    public String getUser_id(){ return getChkNull(user_id); };
    public String getTotal_cnt(){ return getChkNull(total_cnt); };
    public String getKiosk_status(){ return getChkNull(kiosk_status); };
    public String getReg_date(){ return getChkNull(reg_date); };
    public String getShoes_amount(){ return getChkNull(shoes_amount); };
    public String getShoes_name(){ return getChkNull(shoes_name); };
    public String getShoes_price(){ return getChkNull(shoes_price); };
    public String getShoes_explan(){ return getChkNull(shoes_explan); };
    public String getShoes_size(){ return getChkNull(shoes_size); };
    public String getShoes_size_1(){ return getChkNull(shoes_size_1); };
    public String getShoes_size_2(){ return getChkNull(shoes_size_2); };
    public String getShoes_size_3(){ return getChkNull(shoes_size_3); };
    public String getShoes_size_35(){ return getChkNull(shoes_size_35); };
    public String getShoes_size_4(){ return getChkNull(shoes_size_4); };
    public String getShoes_size_45(){ return getChkNull(shoes_size_45); };
    public String getShoes_size_5(){ return getChkNull(shoes_size_5); };
    public String getShoes_size_55(){ return getChkNull(shoes_size_55); };
    public String getShoes_size_6(){ return getChkNull(shoes_size_6); };
    public String getShoes_size_65(){ return getChkNull(shoes_size_65); };
    public String getShoes_size_7(){ return getChkNull(shoes_size_7); };
    public String getShoes_size_75(){ return getChkNull(shoes_size_75); };
    public String getShoes_size_8(){ return getChkNull(shoes_size_8); };
    public String getShoes_size_85(){ return getChkNull(shoes_size_85); };
    public String getShoes_size_9(){ return getChkNull(shoes_size_9); };
    public String getShoes_size_95(){ return getChkNull(shoes_size_95); };
    public String getShoes_size_10(){ return getChkNull(shoes_size_10); };
    public String getShoes_size_105(){ return getChkNull(shoes_size_105); };
    public String getShoes_size_11(){ return getChkNull(shoes_size_11); };
    public String getShoes_size_115(){ return getChkNull(shoes_size_115); };
    public String getShoes_size_12(){ return getChkNull(shoes_size_12); };
    public String getShoes_size_125(){ return getChkNull(shoes_size_125); };
    public String getShoes_size_13(){ return getChkNull(shoes_size_13); };
    public String getShoes_size_14(){ return getChkNull(shoes_size_14); };
    public String getUser_name(){ return getChkNull(user_name); };
    public String getUser_firstname(){ return getChkNull(user_firstname); };
    public String getUser_lastname(){ return getChkNull(user_lastname); };
    public String getUser_phone(){ return getChkNull(user_phone); };
    public String getUser_mail(){ return getChkNull(user_mail); };
    public String getUser_gender(){ return getChkNull(user_gender); };
    public String getUser_age(){ return getChkNull(user_age); };
    public String getUser_birthday(){ return getChkNull(user_birthday); };
    public String getWinner_id(){ return getChkNull(winner_id); };

    public String getM_cnt(){ return getChkNull(m_cnt); };
    public String getF_cnt(){ return getChkNull(f_cnt); };
    public String getTen_cnt(){ return getChkNull(ten_cnt); };
    public String getTwenty_cnt(){ return getChkNull(twenty_cnt); };
    public String getThirty_cnt(){ return getChkNull(thirty_cnt); };
    public String getForty_cnt(){ return getChkNull(forty_cnt); };
    public String getFifty_cnt(){ return getChkNull(fifty_cnt); };
    public String getWinner_choice(){ return getChkNull(winner_choice); };
    

    public String getChkNull(String s){ if(s == null){ return ""; }else{ return s; }   }
    
    
}

